version: "3.0"
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./:/app
    container_name: madhu-test
    labels: 
      - "Under Image column"